source 'http://rubygems.org'

gem 'rails', '3.1.0.rc5'
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "~> 3.1.0.rc"
  gem 'coffee-rails', "~> 3.1.0.rc"
  gem 'uglifier'
end

gem 'jquery-rails'

group :test, :development do
  # To use debugger
  # gem 'ruby-debug19', :require => 'ruby-debug'

  gem "factory_girl_rails", ">= 1.1.0"
  gem "factory_girl_generator", ">= 0.0.3"
  gem "rspec-rails", ">= 2.6.1"
  gem 'RedCloth', '~> 4.2.7'
  gem "capybara"
end
